printWidth: 80 # 每行最大字符数
tabWidth: 2 # 缩进空格数
useTabs: false # 使用空格代替制表符
semi: false # 在语句末尾添加分号
singleQuote: true # 使用单引号（'）代替双引号（"）
quoteProps: 'as-needed' # 仅在需要时为对象属性添加引号
jsxSingleQuote: false # 在JSX中使用双引号
trailingComma: 'all' # 在ES5兼容的地方添加尾随逗号（对象、数组等）
bracketSpacing: true # 在对象字面量的大括号间保留空格（{ foo: bar }）
bracketSameLine: false # 将HTML/JSX元素的闭合标签放在新行
arrowParens: 'always' # 在箭头函数参数周围始终使用括号
proseWrap: 'preserve' # 按原样保留Markdown文本换行
htmlWhitespaceSensitivity: 'css' # 根据CSS样式处理HTML空格
endOfLine: 'auto' # 使用Unix风格的换行符（\n）
embeddedLanguageFormatting: 'auto' # 自动格式化嵌入的代码块
