# .stylelintrc.yaml
extends:
  - stylelint-config-standard # 官方推荐的基础规则集
  - stylelint-config-recommended-scss # SCSS 推荐规则 (如果是 SCSS 项目)
  - stylelint-config-prettier # 兼容 Prettier 的规则

plugins:
  - stylelint-order # 添加 CSS 属性排序规则

rules:
  # 基础规则
  indentation: 2 # 缩进 2 空格
  max-empty-lines: 1 # 最大空行数
  no-empty-first-line: true # 禁止空第一行
  no-eol-whitespace: true # 禁止行尾空格
  no-missing-end-of-source-newline: true # 文件末尾必须有换行

  # CSS 选择器规则
  selector-class-pattern: null # 禁用强制类名格式 (或设置如 ^[a-z][a-zA-Z0-9]+$)
  selector-id-pattern: null # 禁用强制 ID 格式

  # 属性顺序规则 (需 stylelint-order 插件)
  order/properties-order:
    - position
    - top
    - right
    - bottom
    - left
    - display
    - flex
    - align-items
    - justify-content
    # ...其他属性顺序

  # SCSS 特定规则
  scss/at-rule-no-unknown: true
  scss/dollar-variable-pattern: /^[a-z][a-zA-Z0-9]+$/

  # 自定义规则
  color-no-invalid-hex: true
  font-family-no-missing-generic-family-keyword: true
  unit-no-unknown: true

# 忽略检查的文件/目录
ignoreFiles:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/vendor/**'
